### ISSUE TITLE
Sass import

### ISSUE THREAD

**Issue by samirkarimov** [ulvien-pragmatech/Samir-Ustad-PersonalTasks#3]
https://github.com/ulvien-pragmatech/Samir-Ustad-PersonalTasks/blob/5dc6e9743eb9bbb75214a22d7bf15991b5c7f439/Elishi%20toxus/css/_footer.scss#L1

style faylini footer faylina import etmisen Hansi mentiqle? Kicik qutunun icine boyuk qutu qoymaga calismisan

**Comment by ulvien-pragmatech** [comment]
burda uzun code var idi silmisem, test ucun elemisdim hele qalib
